from pathlib import Path

PATH = Path("supabase/functions/atis-harpa-study/index.ts")
text = PATH.read_text()

old = '''    const theme = compactField(analysis.theme, "Tema central não identificado com segurança.", 320);\n    const explanation = compactField(analysis.explanation, "A letra aponta para uma mensagem cristã que deve ser lida à luz das Escrituras.", conversationMode === "study" ? 1500 : 900);\n    const application = compactField(analysis.application, "Use a mensagem do hino como convite à reflexão e à prática da fé cristã.", 700);\n\n    const rawReferences = Array.isArray(analysis.references) ? analysis.references.filter((item: unknown) => typeof item === "string").slice(0, 6) : [];\n'''
new = '''    const rawTheme = compactField(analysis.theme, "Tema central não identificado com segurança.", 320);\n    const rawExplanation = compactField(analysis.explanation, "A letra aponta para uma mensagem cristã que deve ser lida à luz das Escrituras.", conversationMode === "study" ? 1500 : 900);\n    const rawApplication = compactField(analysis.application, "Use a mensagem do hino como convite à reflexão e à prática da fé cristã.", 700);\n\n    const rawReferences = Array.isArray(analysis.references) ? analysis.references.filter((item: unknown) => typeof item === "string").slice(0, 6) : [];\n'''
if text.count(old) != 1:
    raise SystemExit(f"analysis fields anchor mismatch: {text.count(old)}")
text = text.replace(old, new, 1)

old = '''    const bibleBlock = verified.length\n      ? `\\n\\n*Conexões bíblicas verificadas na Bíblia do Atalaia (${config.bibleVersion}):*\\n${verified.map((item) => `📖 *${item.label}*\\n${item.text}`).join("\\n\\n")}`\n      : "\\n\\n📖 Não incluí conexões bíblicas textuais porque nenhuma referência sugerida passou pela validação do acervo do app nesta resposta.";\n\n    const answer = clampText(`🎵 *Estudo da Harpa Cristã ${hymn.numero} — ${title}*\\n\\n*Tema:* ${theme}\\n\\n*Leitura do hino:* ${explanation}\\n\\n*Aplicação:* ${application}${bibleBlock}`);\n'''
new = '''    const verifiedKeys = new Set(verified.map((item) => normalize(item.label)));\n    const sanitizeNarrative = (value: string) => {\n      const withoutLongQuotes = value\n        .replace(/“([^”\\n]{24,})”/g, "(trecho literal omitido; consulte as conexões verificadas abaixo)")\n        .replace(/\"([^\"\\n]{24,})\"/g, "(trecho literal omitido; consulte as conexões verificadas abaixo)");\n      return withoutLongQuotes.replace(/\\b(?:[1-3]\\s+)?[A-Za-zÀ-ÿ]+(?:\\s+[A-Za-zÀ-ÿ]+){0,3}\\s+\\d{1,3}:\\s*\\d{1,3}(?:\\s*[-–]\\s*\\d{1,3})?/gu, (candidate) => {\n        const reference = resolveBibleReference(candidate, bible);\n        if (!reference) return candidate;\n        const canonical = bibleExcerpt(reference).label;\n        return verifiedKeys.has(normalize(canonical)) ? canonical : "uma passagem bíblica relacionada";\n      });\n    };\n\n    const theme = sanitizeNarrative(rawTheme);\n    const explanation = sanitizeNarrative(rawExplanation);\n    const application = sanitizeNarrative(rawApplication);\n\n    const bibleBlock = verified.length\n      ? `\\n\\n*Conexões bíblicas verificadas na Bíblia do Atalaia (${config.bibleVersion}):*\\n${verified.map((item) => `📖 *${item.label}*\\n${item.text}`).join("\\n\\n")}`\n      : "\\n\\n📖 Não incluí conexões bíblicas textuais porque nenhuma referência sugerida passou pela validação do acervo do app nesta resposta.";\n\n    const answer = clampText(`🎵 *Estudo da Harpa Cristã ${hymn.numero} — ${title}*\\n\\n*Tema:* ${theme}\\n\\n*Leitura do hino:* ${explanation}\\n\\n*Aplicação:* ${application}${bibleBlock}`);\n'''
if text.count(old) != 1:
    raise SystemExit(f"grounding block anchor mismatch: {text.count(old)}")
text = text.replace(old, new, 1)
PATH.write_text(text)
print("ATIS Harpa study v33b hardening applied")
