create extension if not exists vector with schema extensions;

create table if not exists public.atis_bible_semantic_chunks (
  id bigint generated by default as identity primary key,
  bible_version text not null default 'ARC',
  book_name text not null,
  book_abbrev text not null,
  chapter integer not null check (chapter > 0),
  verse_start integer not null check (verse_start > 0),
  verse_end integer not null check (verse_end >= verse_start),
  reference text not null,
  content text not null,
  content_hash text not null,
  embedding extensions.vector(768),
  embedding_model text,
  embedded_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (bible_version, book_abbrev, chapter, verse_start, verse_end)
);

alter table public.atis_bible_semantic_chunks enable row level security;
revoke all on table public.atis_bible_semantic_chunks from anon, authenticated;
grant select, insert, update, delete on table public.atis_bible_semantic_chunks to service_role;
grant usage, select on sequence public.atis_bible_semantic_chunks_id_seq to service_role;

create index if not exists atis_bible_semantic_chunks_reference_idx
  on public.atis_bible_semantic_chunks (bible_version, book_abbrev, chapter, verse_start, verse_end);

create index if not exists atis_bible_semantic_chunks_embedding_hnsw_idx
  on public.atis_bible_semantic_chunks
  using hnsw (embedding extensions.vector_cosine_ops)
  where embedding is not null;

create or replace function public.atis_bible_semantic_search(
  _embedding extensions.vector(768),
  _match_count integer default 18,
  _min_similarity double precision default 0.42,
  _bible_version text default 'ARC'
)
returns table (
  id bigint,
  reference text,
  content text,
  book_name text,
  book_abbrev text,
  chapter integer,
  verse_start integer,
  verse_end integer,
  similarity double precision
)
language sql
stable
security definer
set search_path = public, extensions
as $$
  select
    c.id,
    c.reference,
    c.content,
    c.book_name,
    c.book_abbrev,
    c.chapter,
    c.verse_start,
    c.verse_end,
    (1 - (c.embedding <=> _embedding))::double precision as similarity
  from public.atis_bible_semantic_chunks c
  where c.embedding is not null
    and c.bible_version = coalesce(nullif(_bible_version, ''), 'ARC')
    and (1 - (c.embedding <=> _embedding)) >= greatest(0.0, least(coalesce(_min_similarity, 0.42), 1.0))
  order by c.embedding <=> _embedding
  limit greatest(1, least(coalesce(_match_count, 18), 40));
$$;

revoke all on function public.atis_bible_semantic_search(extensions.vector, integer, double precision, text) from public, anon, authenticated;
grant execute on function public.atis_bible_semantic_search(extensions.vector, integer, double precision, text) to service_role;

create or replace function public.atis_bible_semantic_store_embeddings(_rows jsonb)
returns integer
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  _row jsonb;
  _count integer := 0;
begin
  if jsonb_typeof(_rows) <> 'array' then
    raise exception '_rows must be a JSON array';
  end if;

  for _row in select value from jsonb_array_elements(_rows)
  loop
    update public.atis_bible_semantic_chunks
       set embedding = ((_row -> 'embedding')::text)::extensions.vector(768),
           embedding_model = coalesce(nullif(_row ->> 'model', ''), 'gemini-embedding-2'),
           embedded_at = now(),
           updated_at = now()
     where id = (_row ->> 'id')::bigint;
    if found then _count := _count + 1; end if;
  end loop;
  return _count;
end;
$$;

revoke all on function public.atis_bible_semantic_store_embeddings(jsonb) from public, anon, authenticated;
grant execute on function public.atis_bible_semantic_store_embeddings(jsonb) to service_role;

create or replace function public.atis_bible_semantic_progress()
returns table(total bigint, embedded bigint, pending bigint)
language sql
stable
security definer
set search_path = public
as $$
  select
    count(*)::bigint,
    count(*) filter (where embedding is not null)::bigint,
    count(*) filter (where embedding is null)::bigint
  from public.atis_bible_semantic_chunks;
$$;

revoke all on function public.atis_bible_semantic_progress() from public, anon, authenticated;
grant execute on function public.atis_bible_semantic_progress() to service_role;
